# yaml-language-server: $schema=https://json.schemastore.org/commitlintrc.json
---
extends:
  - '@commitlint/config-conventional'

rules:
  type-enum:
    - 2
    - always
    - - feat
      - fix
      - docs
      - style
      - refactor
      - perf
      - test
      - chore
      - ci
      - build
      - revert
  subject-case:
    - 2
    - never
    - - start-case
      - pascal-case
      - upper-case
