import { ConfigurableModuleBuilder } from '@nestjs/common';

import { TwilioModuleOptions } from './twilio.interface.js';

/**
 * The module blueprint generated by Nest's `ConfigurableModuleBuilder`.
 *
 * There is deliberately no `isGlobal` extra. `TwilioModule.forRoot()` always
 * registers globally, matching `TypeOrmCoreModule`, Mongoose's core module and
 * `BullModule.forRoot()` — every one of which sets `global: true`. Beyond
 * convention, it is what makes `registerClient()` able to inherit the shared
 * options: a named client is registered as its own module, and a non-global
 * root would be invisible to it, so inheritance would depend on a user flag
 * and silently stop working when it was switched off.
 */
export const { ConfigurableModuleClass, MODULE_OPTIONS_TOKEN, OPTIONS_TYPE, ASYNC_OPTIONS_TYPE } =
  new ConfigurableModuleBuilder<TwilioModuleOptions>().setClassMethodName('forRoot').build();
